//go:build !windows

package util

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestSysDNSServersFromResolvConf(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "resolv.conf")

	content := `# generated by systemd-resolved
nameserver 223.5.5.5
nameserver 119.29.29.29
nameserver 2400:3200::1

search example.com
options timeout:1
`
	assert.NoError(t, os.WriteFile(path, []byte(content), 0600))

	servers, err := sysDNSServersFromResolvConf(path)
	assert.NoError(t, err)
	assert.Equal(t, []string{"223.5.5.5", "119.29.29.29", "2400:3200::1"}, servers)
}

func TestSysDNSServersFromResolvConfEmpty(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "resolv.conf")

	assert.NoError(t, os.WriteFile(path, []byte("# no nameserver\n"), 0600))

	servers, err := sysDNSServersFromResolvConf(path)
	assert.NoError(t, err)
	assert.Empty(t, servers)
}

func TestSysDNSServersFromResolvConfNotFound(t *testing.T) {
	_, err := sysDNSServersFromResolvConf(filepath.Join(t.TempDir(), "not-exist.conf"))
	assert.Error(t, err)
}
