name: Nightly Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install gomobile
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          export PATH="$(go env GOPATH)/bin:$PATH"
          gomobile init

      - name: Build
        run: make .PHONY

      - name: Pack
        run: |
          cd bin
          zip easyss-linux-amd64.zip ./easyss
          zip easyss-windows-amd64.zip ./easyss.exe
          zip easyss-headless-linux-amd64.zip ./easyss-headless
          zip easyss-server-linux-amd64.zip ./easyss-server
          zip easyss-server-windows-amd64.zip ./easyss-server.exe

      - name: Build Linux Arm64
        run: |
          GOOS=linux GOARCH=arm64 make easyss
          GOOS=linux GOARCH=arm64 make easyss-headless
          GOOS=linux GOARCH=arm64 make easyss-server
      - name: Pack Linux Arm64
        run: |
          cd bin
          zip easyss-linux-arm64.zip ./easyss
          zip easyss-headless-linux-arm64.zip ./easyss-headless
          zip easyss-server-linux-arm64.zip ./easyss-server

      - name: Build Windows Arm64
        run: make easyss-windows easyss-server-windows WIN_ARCH=arm64
      - name: Pack Windows Arm64
        run: |
          cd bin
          zip easyss-windows-arm64.zip ./easyss.exe
          zip easyss-server-windows-arm64.zip ./easyss-server.exe

      - name: Build MacOS Arm64
        run: |
          GOOS=darwin GOARCH=arm64 make easyss-mac-app
          GOOS=darwin GOARCH=arm64 make easyss-server
      - name: Pack MacOS Arm64
        run: |
          cd bin
          zip -r easyss-darwin-arm64.zip ./Easyss.app
          zip easyss-server-darwin-arm64.zip ./easyss-server

      - name: Build MacOS Amd64
        run: |
          GOOS=darwin GOARCH=amd64 make easyss-mac-app
          GOOS=darwin GOARCH=amd64 make easyss-server
      - name: Pack MacOS Amd64
        run: |
          cd bin
          zip -r easyss-darwin-amd64.zip ./Easyss.app
          zip easyss-server-darwin-amd64.zip ./easyss-server

      - name: Set outputs
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "timestamp_minute=$(date -u +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT

      - name: Nightly Release
        uses: softprops/action-gh-release@v3
        with:
          name: Nightly-${{ steps.vars.outputs.timestamp_minute }}-${{ steps.vars.outputs.sha_short }}
          tag_name: nightly-${{ steps.vars.outputs.sha_short }}
          prerelease: true
          body: For testing and development only
          files: |
            bin/*.zip
            bin/*.aar
