name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - name: Install Deps
        run: sudo apt update && sudo apt install -y libgtk-3-dev libayatana-appindicator3-dev

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build
        run: make .PHONY
      - name: Build Android AAR
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          gomobile init
          make easyss-android-aar

      - name: Pack
        run: |
          cd bin
          zip easyss-linux-amd64.zip ./easyss
          zip easyss-windows-amd64.zip ./easyss.exe
          zip easyss-without-tray-linux-amd64.zip ./easyss-without-tray
          zip easyss-server-linux-amd64.zip ./easyss-server
          zip easyss-server-windows-amd64.zip ./easyss-server.exe

      - name: Build Arm64
        run: |
          GOOS=linux GOARCH=arm64 make easyss-without-tray
          GOOS=linux GOARCH=arm64 make easyss-server
      - name: Pack Arm64
        run: |
          cd bin
          zip easyss-without-tray-linux-arm64.zip ./easyss-without-tray
          zip easyss-server-linux-arm64.zip ./easyss-server

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-artifacts
          path: |
            bin/*.zip
            bin/*.aar

  macos-arm64:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'

      - name: Build Arm64
        run: |
          GOOS=darwin GOARCH=arm64 make easyss
          GOOS=darwin GOARCH=arm64 make easyss-server
      - name: Pack Arm64
        run: |
          cd bin
          zip easyss-darwin-arm64.zip ./easyss
          zip easyss-server-darwin-arm64.zip ./easyss-server
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-arm64-artifacts
          path: bin/*.zip

  macos-amd64:
    runs-on: macos-15-intel
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'
      - name: Build Amd64
        run: |
          GOOS=darwin GOARCH=amd64 make easyss
          GOOS=darwin GOARCH=amd64 make easyss-server
      - name: Pack Amd64
        run: |
          cd bin
          zip easyss-darwin-amd64.zip ./easyss
          zip easyss-server-darwin-amd64.zip ./easyss-server
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-amd64-artifacts
          path: bin/*.zip

  release:
    runs-on: ubuntu-22.04
    needs:
      - linux
      - macos-arm64
      - macos-amd64
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
          files: |
            artifacts/*.zip
            artifacts/*.aar
